BaseConfig:
  minDetectorConfidence: 0.25

TargetManagement:
  maxTargetsPerStream: 150
  probationAge: 20
  maxShadowTrackingAge: 60
  earlyTerminationAge: 15

DataAssociator:
  associationMatcherType: 1   # IoU
  checkClassMatch: 1
  minMatchingScore4Iou: 0.35

StateEstimator:
  stateEstimatorType: 2       # Kalman
